
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.froi.pruebas.gramaticas;

/** CUP generated class containing symbol constants. */
public class EtiquetadoParserSym {
  /* terminals */
  public static final int IDENTIFICADOR = 95;
  public static final int FONTFAMILY = 23;
  public static final int DIVISION = 82;
  public static final int BARRA = 84;
  public static final int MENOR_IGUAL = 73;
  public static final int MENOR_QUE = 72;
  public static final int H1 = 16;
  public static final int TYPE = 25;
  public static final int ROWS = 29;
  public static final int DIAGONAL = 85;
  public static final int ASC = 36;
  public static final int NAME = 27;
  public static final int TEXTO = 97;
  public static final int INIT = 46;
  public static final int ALT = 34;
  public static final int COM_SIMP = 94;
  public static final int LETIMPAR_NUM = 39;
  public static final int INTEGER = 58;
  public static final int MAYOR_QUE = 74;
  public static final int IGUAL_IGUAL = 70;
  public static final int PROCESS = 57;
  public static final int NOT = 78;
  public static final int FALSE = 67;
  public static final int BACKGROUND = 20;
  public static final int D_CHAR = 68;
  public static final int THENWHILE = 54;
  public static final int THEN = 49;
  public static final int WIDTH = 32;
  public static final int REVERSE = 40;
  public static final int PARC = 87;
  public static final int PUNTO_COMA = 92;
  public static final int PARA = 86;
  public static final int CLASS = 30;
  public static final int ALERT_INFO = 43;
  public static final int SELECT = 10;
  public static final int TEXTAREA = 9;
  public static final int D_INTEGER = 64;
  public static final int NUM_ALEATORIO = 42;
  public static final int HUNTIL = 52;
  public static final int TRUE = 66;
  public static final int IGUAL = 83;
  public static final int WHILE = 53;
  public static final int COLS = 28;
  public static final int DECIMAL = 59;
  public static final int CHAR = 61;
  public static final int BOOLEAN = 60;
  public static final int TEXTALIGN = 24;
  public static final int INPUT = 8;
  public static final int GCIC = 2;
  public static final int DIV = 12;
  public static final int PUNTOS = 93;
  public static final int P = 17;
  public static final int ELSE = 50;
  public static final int CORC = 89;
  public static final int CORA = 88;
  public static final int LINK = 5;
  public static final int EOF = 0;
  public static final int SUMA = 79;
  public static final int BUTTON = 15;
  public static final int REPEAT = 51;
  public static final int LLAC = 91;
  public static final int SPAM = 7;
  public static final int LLAA = 90;
  public static final int SCRIPTING = 18;
  public static final int SRC = 31;
  public static final int BODY = 6;
  public static final int HREF = 19;
  public static final int TITLE = 4;
  public static final int D_STRING = 69;
  public static final int OR = 76;
  public static final int error = 1;
  public static final int EXIT = 44;
  public static final int RESTA = 80;
  public static final int IF = 48;
  public static final int DESC = 37;
  public static final int ID = 26;
  public static final int COLOR = 21;
  public static final int ON_LOAD = 56;
  public static final int HEAD = 3;
  public static final int END = 47;
  public static final int D_DECIMAL = 65;
  public static final int MULTIPLICACION = 81;
  public static final int IMG = 13;
  public static final int FONTSIZE = 22;
  public static final int HEIGHT = 33;
  public static final int BR = 14;
  public static final int GLOBAL = 63;
  public static final int ALFANUMERICO = 96;
  public static final int CARACTER_ALEATORIO = 41;
  public static final int DIFERENTE_IGUAL = 71;
  public static final int OPTION = 11;
  public static final int INSERT = 55;
  public static final int STRING = 62;
  public static final int ONCLICK = 35;
  public static final int AND = 77;
  public static final int LETPAR_NUM = 38;
  public static final int MAYOR_IGUAL = 75;
  public static final int GETBYID = 45;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "GCIC",
  "HEAD",
  "TITLE",
  "LINK",
  "BODY",
  "SPAM",
  "INPUT",
  "TEXTAREA",
  "SELECT",
  "OPTION",
  "DIV",
  "IMG",
  "BR",
  "BUTTON",
  "H1",
  "P",
  "SCRIPTING",
  "HREF",
  "BACKGROUND",
  "COLOR",
  "FONTSIZE",
  "FONTFAMILY",
  "TEXTALIGN",
  "TYPE",
  "ID",
  "NAME",
  "COLS",
  "ROWS",
  "CLASS",
  "SRC",
  "WIDTH",
  "HEIGHT",
  "ALT",
  "ONCLICK",
  "ASC",
  "DESC",
  "LETPAR_NUM",
  "LETIMPAR_NUM",
  "REVERSE",
  "CARACTER_ALEATORIO",
  "NUM_ALEATORIO",
  "ALERT_INFO",
  "EXIT",
  "GETBYID",
  "INIT",
  "END",
  "IF",
  "THEN",
  "ELSE",
  "REPEAT",
  "HUNTIL",
  "WHILE",
  "THENWHILE",
  "INSERT",
  "ON_LOAD",
  "PROCESS",
  "INTEGER",
  "DECIMAL",
  "BOOLEAN",
  "CHAR",
  "STRING",
  "GLOBAL",
  "D_INTEGER",
  "D_DECIMAL",
  "TRUE",
  "FALSE",
  "D_CHAR",
  "D_STRING",
  "IGUAL_IGUAL",
  "DIFERENTE_IGUAL",
  "MENOR_QUE",
  "MENOR_IGUAL",
  "MAYOR_QUE",
  "MAYOR_IGUAL",
  "OR",
  "AND",
  "NOT",
  "SUMA",
  "RESTA",
  "MULTIPLICACION",
  "DIVISION",
  "IGUAL",
  "BARRA",
  "DIAGONAL",
  "PARA",
  "PARC",
  "CORA",
  "CORC",
  "LLAA",
  "LLAC",
  "PUNTO_COMA",
  "PUNTOS",
  "COM_SIMP",
  "IDENTIFICADOR",
  "ALFANUMERICO",
  "TEXTO"
  };
}
