
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.froi.gcic.gramaticas.almacenamiento;

/** CUP generated class containing symbol constants. */
public class GuardadoParserSym {
  /* terminals */
  public static final int PUNTOS = 15;
  public static final int COMA = 14;
  public static final int LLAC = 13;
  public static final int LLAA = 12;
  public static final int FALLOS = 9;
  public static final int EOF = 0;
  public static final int CANTUSOS = 7;
  public static final int ID = 3;
  public static final int LINK = 5;
  public static final int error = 1;
  public static final int ALLCHAR = 16;
  public static final int PARC = 11;
  public static final int ACIERTOS = 8;
  public static final int DBCAPTCHAS = 2;
  public static final int NOMBRE = 4;
  public static final int PARA = 10;
  public static final int PATH = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "DBCAPTCHAS",
  "ID",
  "NOMBRE",
  "LINK",
  "PATH",
  "CANTUSOS",
  "ACIERTOS",
  "FALLOS",
  "PARA",
  "PARC",
  "LLAA",
  "LLAC",
  "COMA",
  "PUNTOS",
  "ALLCHAR"
  };
}

