
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.froi.pruebas.gramaticas;

/** CUP generated class containing symbol constants. */
public class EtiquetadoParserSym {
  /* terminals */
  public static final int IDENTIFICADOR = 129;
  public static final int AQUA = 51;
  public static final int LEFT = 60;
  public static final int FONTFAMILY = 23;
  public static final int HEXADECIMAL = 52;
  public static final int DIVISION = 116;
  public static final int BARRA = 118;
  public static final int MENOR_IGUAL = 107;
  public static final int MENOR_QUE = 106;
  public static final int COLUMN = 69;
  public static final int H1 = 16;
  public static final int TYPE = 25;
  public static final int TEAL = 38;
  public static final int RIGHT = 61;
  public static final int ROWS = 29;
  public static final int DIAGONAL = 119;
  public static final int ASC = 70;
  public static final int CHECKBOX = 67;
  public static final int NAME = 27;
  public static final int ROW = 68;
  public static final int TEXTO = 131;
  public static final int MAROON = 41;
  public static final int SANS_SERIF = 59;
  public static final int INIT = 80;
  public static final int BLUE = 40;
  public static final int ALT = 34;
  public static final int YELLOW = 50;
  public static final int FUCHSIA = 45;
  public static final int WHITE = 47;
  public static final int COM_SIMP = 128;
  public static final int LETIMPAR_NUM = 73;
  public static final int INTEGER = 92;
  public static final int BLACK = 36;
  public static final int MAYOR_QUE = 108;
  public static final int GRAY = 43;
  public static final int IGUAL_IGUAL = 104;
  public static final int PIXELES = 53;
  public static final int PROCESS = 91;
  public static final int NOT = 112;
  public static final int D_CHAR = 102;
  public static final int FALSE = 101;
  public static final int BACKGROUND = 20;
  public static final int CENTER = 62;
  public static final int TEXT = 64;
  public static final int THENWHILE = 88;
  public static final int THEN = 83;
  public static final int PURPLE = 48;
  public static final int WIDTH = 32;
  public static final int REVERSE = 74;
  public static final int PARC = 121;
  public static final int PUNTO_COMA = 126;
  public static final int PARA = 120;
  public static final int CLASS = 30;
  public static final int ALERT_INFO = 77;
  public static final int SELECT = 10;
  public static final int NUMBER = 65;
  public static final int TEXTAREA = 9;
  public static final int D_INTEGER = 98;
  public static final int NUM_ALEATORIO = 76;
  public static final int HUNTIL = 86;
  public static final int TRUE = 100;
  public static final int IGUAL = 117;
  public static final int OLIVE = 37;
  public static final int WHILE = 87;
  public static final int COLS = 28;
  public static final int PORCENTAJE = 54;
  public static final int ALLCHAR = 132;
  public static final int CHAR = 95;
  public static final int DECIMAL = 93;
  public static final int BOOLEAN = 94;
  public static final int JUSTIFY = 63;
  public static final int TEXTALIGN = 24;
  public static final int INPUT = 8;
  public static final int GCIC = 2;
  public static final int DIV = 12;
  public static final int PUNTOS = 127;
  public static final int NAVY = 42;
  public static final int P = 17;
  public static final int ELSE = 84;
  public static final int CORC = 123;
  public static final int COURIER = 55;
  public static final int CORA = 122;
  public static final int DIGITO_COM = 134;
  public static final int LINK = 5;
  public static final int EOF = 0;
  public static final int ARIAL = 57;
  public static final int SUMA = 113;
  public static final int BUTTON = 15;
  public static final int REPEAT = 85;
  public static final int LLAC = 125;
  public static final int SPAM = 7;
  public static final int LLAA = 124;
  public static final int VERDANA = 56;
  public static final int GENEVA = 58;
  public static final int SCRIPTING = 18;
  public static final int SRC = 31;
  public static final int D_STRING = 103;
  public static final int BODY = 6;
  public static final int HREF = 19;
  public static final int TITLE = 4;
  public static final int OR = 110;
  public static final int EXIT = 78;
  public static final int error = 1;
  public static final int RESTA = 114;
  public static final int IF = 82;
  public static final int DESC = 71;
  public static final int ID = 26;
  public static final int COLOR = 21;
  public static final int ON_LOAD = 90;
  public static final int HEAD = 3;
  public static final int END = 81;
  public static final int D_DECIMAL = 99;
  public static final int SILVER = 49;
  public static final int MULTIPLICACION = 115;
  public static final int LIME = 44;
  public static final int IMG = 13;
  public static final int FONTSIZE = 22;
  public static final int RADIO = 66;
  public static final int HEIGHT = 33;
  public static final int BR = 14;
  public static final int RED = 39;
  public static final int GLOBAL = 97;
  public static final int ALFANUMERICO = 130;
  public static final int CARACTER_ALEATORIO = 75;
  public static final int DIFERENTE_IGUAL = 105;
  public static final int OPTION = 11;
  public static final int INSERT = 89;
  public static final int STRING = 96;
  public static final int ONCLICK = 35;
  public static final int AND = 111;
  public static final int ALLCHARNOSPACE = 133;
  public static final int LETPAR_NUM = 72;
  public static final int MAYOR_IGUAL = 109;
  public static final int GETBYID = 79;
  public static final int GREEN = 46;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "GCIC",
  "HEAD",
  "TITLE",
  "LINK",
  "BODY",
  "SPAM",
  "INPUT",
  "TEXTAREA",
  "SELECT",
  "OPTION",
  "DIV",
  "IMG",
  "BR",
  "BUTTON",
  "H1",
  "P",
  "SCRIPTING",
  "HREF",
  "BACKGROUND",
  "COLOR",
  "FONTSIZE",
  "FONTFAMILY",
  "TEXTALIGN",
  "TYPE",
  "ID",
  "NAME",
  "COLS",
  "ROWS",
  "CLASS",
  "SRC",
  "WIDTH",
  "HEIGHT",
  "ALT",
  "ONCLICK",
  "BLACK",
  "OLIVE",
  "TEAL",
  "RED",
  "BLUE",
  "MAROON",
  "NAVY",
  "GRAY",
  "LIME",
  "FUCHSIA",
  "GREEN",
  "WHITE",
  "PURPLE",
  "SILVER",
  "YELLOW",
  "AQUA",
  "HEXADECIMAL",
  "PIXELES",
  "PORCENTAJE",
  "COURIER",
  "VERDANA",
  "ARIAL",
  "GENEVA",
  "SANS_SERIF",
  "LEFT",
  "RIGHT",
  "CENTER",
  "JUSTIFY",
  "TEXT",
  "NUMBER",
  "RADIO",
  "CHECKBOX",
  "ROW",
  "COLUMN",
  "ASC",
  "DESC",
  "LETPAR_NUM",
  "LETIMPAR_NUM",
  "REVERSE",
  "CARACTER_ALEATORIO",
  "NUM_ALEATORIO",
  "ALERT_INFO",
  "EXIT",
  "GETBYID",
  "INIT",
  "END",
  "IF",
  "THEN",
  "ELSE",
  "REPEAT",
  "HUNTIL",
  "WHILE",
  "THENWHILE",
  "INSERT",
  "ON_LOAD",
  "PROCESS",
  "INTEGER",
  "DECIMAL",
  "BOOLEAN",
  "CHAR",
  "STRING",
  "GLOBAL",
  "D_INTEGER",
  "D_DECIMAL",
  "TRUE",
  "FALSE",
  "D_CHAR",
  "D_STRING",
  "IGUAL_IGUAL",
  "DIFERENTE_IGUAL",
  "MENOR_QUE",
  "MENOR_IGUAL",
  "MAYOR_QUE",
  "MAYOR_IGUAL",
  "OR",
  "AND",
  "NOT",
  "SUMA",
  "RESTA",
  "MULTIPLICACION",
  "DIVISION",
  "IGUAL",
  "BARRA",
  "DIAGONAL",
  "PARA",
  "PARC",
  "CORA",
  "CORC",
  "LLAA",
  "LLAC",
  "PUNTO_COMA",
  "PUNTOS",
  "COM_SIMP",
  "IDENTIFICADOR",
  "ALFANUMERICO",
  "TEXTO",
  "ALLCHAR",
  "ALLCHARNOSPACE",
  "DIGITO_COM"
  };
}

