
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class InsertParserSym {
  /* terminals */
  public static final int AQUA = 51;
  public static final int LEFT = 60;
  public static final int FONTFAMILY = 23;
  public static final int HEXADECIMAL = 52;
  public static final int MENOR_QUE = 76;
  public static final int COLUMN = 69;
  public static final int H1 = 16;
  public static final int TYPE = 25;
  public static final int TEAL = 38;
  public static final int RIGHT = 61;
  public static final int ROWS = 29;
  public static final int CHECKBOX = 67;
  public static final int NAME = 27;
  public static final int ROW = 68;
  public static final int TEXTO = 72;
  public static final int MAROON = 41;
  public static final int SANS_SERIF = 59;
  public static final int BLUE = 40;
  public static final int ALT = 34;
  public static final int YELLOW = 50;
  public static final int FUCHSIA = 45;
  public static final int WHITE = 47;
  public static final int BLACK = 36;
  public static final int MAYOR_QUE = 78;
  public static final int GRAY = 43;
  public static final int PIXELES = 53;
  public static final int BACKGROUND = 20;
  public static final int CENTER = 62;
  public static final int TEXT = 64;
  public static final int PURPLE = 48;
  public static final int WIDTH = 32;
  public static final int CLASS = 30;
  public static final int SELECT = 10;
  public static final int NUMBER = 65;
  public static final int TEXTAREA = 9;
  public static final int IGUAL = 81;
  public static final int OLIVE = 37;
  public static final int COLS = 28;
  public static final int PORCENTAJE = 54;
  public static final int ALLCHAR = 73;
  public static final int JUSTIFY = 63;
  public static final int TEXTALIGN = 24;
  public static final int INPUT = 8;
  public static final int GCIC = 2;
  public static final int DIV = 12;
  public static final int NAVY = 42;
  public static final int MENOR_CIERRE = 77;
  public static final int P = 17;
  public static final int CORC = 80;
  public static final int COURIER = 55;
  public static final int CORA = 79;
  public static final int DIGITO_COM = 75;
  public static final int LINK = 5;
  public static final int EOF = 0;
  public static final int ARIAL = 57;
  public static final int BUTTON = 15;
  public static final int SPAM = 7;
  public static final int VERDANA = 56;
  public static final int GENEVA = 58;
  public static final int SCRIPTING = 18;
  public static final int SRC = 31;
  public static final int ID_ETIQUETA = 70;
  public static final int BODY = 6;
  public static final int HREF = 19;
  public static final int TITLE = 4;
  public static final int error = 1;
  public static final int ID = 26;
  public static final int COLOR = 21;
  public static final int HEAD = 3;
  public static final int SILVER = 49;
  public static final int LIME = 44;
  public static final int IMG = 13;
  public static final int FONTSIZE = 22;
  public static final int RADIO = 66;
  public static final int HEIGHT = 33;
  public static final int BR = 14;
  public static final int RED = 39;
  public static final int ALFANUMERICO = 71;
  public static final int OPTION = 11;
  public static final int ONCLICK = 35;
  public static final int ALLCHARNOSPACE = 74;
  public static final int GREEN = 46;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "GCIC",
  "HEAD",
  "TITLE",
  "LINK",
  "BODY",
  "SPAM",
  "INPUT",
  "TEXTAREA",
  "SELECT",
  "OPTION",
  "DIV",
  "IMG",
  "BR",
  "BUTTON",
  "H1",
  "P",
  "SCRIPTING",
  "HREF",
  "BACKGROUND",
  "COLOR",
  "FONTSIZE",
  "FONTFAMILY",
  "TEXTALIGN",
  "TYPE",
  "ID",
  "NAME",
  "COLS",
  "ROWS",
  "CLASS",
  "SRC",
  "WIDTH",
  "HEIGHT",
  "ALT",
  "ONCLICK",
  "BLACK",
  "OLIVE",
  "TEAL",
  "RED",
  "BLUE",
  "MAROON",
  "NAVY",
  "GRAY",
  "LIME",
  "FUCHSIA",
  "GREEN",
  "WHITE",
  "PURPLE",
  "SILVER",
  "YELLOW",
  "AQUA",
  "HEXADECIMAL",
  "PIXELES",
  "PORCENTAJE",
  "COURIER",
  "VERDANA",
  "ARIAL",
  "GENEVA",
  "SANS_SERIF",
  "LEFT",
  "RIGHT",
  "CENTER",
  "JUSTIFY",
  "TEXT",
  "NUMBER",
  "RADIO",
  "CHECKBOX",
  "ROW",
  "COLUMN",
  "ID_ETIQUETA",
  "ALFANUMERICO",
  "TEXTO",
  "ALLCHAR",
  "ALLCHARNOSPACE",
  "DIGITO_COM",
  "MENOR_QUE",
  "MENOR_CIERRE",
  "MAYOR_QUE",
  "CORA",
  "CORC",
  "IGUAL"
  };
}

